from smsbomber import Bomber

num = input("请输入手机号:")

Bomber(num).func0()
Bomber(num).func1()
Bomber(num).func2()
Bomber(num).func3()
Bomber(num).func4()
Bomber(num).func5()
Bomber(num).func6()
Bomber(num).func7()
Bomber(num).func8()
Bomber(num).func9()
Bomber(num).func10()
Bomber(num).func11()
Bomber(num).func12()
Bomber(num).func13()
Bomber(num).func14()
Bomber(num).func15()
Bomber(num).func16()
Bomber(num).func17()
Bomber(num).func18()
Bomber(num).func19()
Bomber(num).func20()
